capstone_project/Controllers/InquiriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using capstone_project.Models;

namespace capstone_project.Controllers
{
    public class InquiriesController : Controller
    {
        private capstone_mwdEntities db = new capstone_mwdEntities();

        // GET: Inquiries
        public ActionResult Index()
        {
            var tbl_inquiries = db.tbl_inquiries.Include(t => t.tbl_accounts).Include(t => t.tbl_accounts1).Include(t => t.tbl_threads);
            return View(tbl_inquiries.ToList());
        }

        // GET: Inquiries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_inquiries tbl_inquiries = db.tbl_inquiries.Find(id);
            if (tbl_inquiries == null)
            {
                return HttpNotFound();
            }
            return View(tbl_inquiries);
        }

        // GET: Inquiries/Create
        public ActionResult Create()
        {
            ViewBag.inq_from = new SelectList(db.tbl_accounts, "account_id", "account_email");
            ViewBag.inq_to = new SelectList(db.tbl_accounts, "account_id", "account_email");
            ViewBag.thread_id = new SelectList(db.tbl_threads, "thread_id", "thread_title");
            return View();
        }

        // POST: Inquiries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "inq_id,inq_content,inq_date,inq_from,inq_to,thread_id")] tbl_inquiries tbl_inquiries)
        {
            if (ModelState.IsValid)
            {
                db.tbl_inquiries.Add(tbl_inquiries);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.inq_from = new SelectList(db.tbl_accounts, "account_id", "account_email", tbl_inquiries.inq_from);
            ViewBag.inq_to = new SelectList(db.tbl_accounts, "account_id", "account_email", tbl_inquiries.inq_to);
            ViewBag.thread_id = new SelectList(db.tbl_threads, "thread_id", "thread_title", tbl_inquiries.thread_id);
            return View(tbl_inquiries);
        }

        // GET: Inquiries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_inquiries tbl_inquiries = db.tbl_inquiries.Find(id);
            if (tbl_inquiries == null)
            {
                return HttpNotFound();
            }
            ViewBag.inq_from = new SelectList(db.tbl_accounts, "account_id", "account_email", tbl_inquiries.inq_from);
            ViewBag.inq_to = new SelectList(db.tbl_accounts, "account_id", "account_email", tbl_inquiries.inq_to);
            ViewBag.thread_id = new SelectList(db.tbl_threads, "thread_id", "thread_title", tbl_inquiries.thread_id);
            return View(tbl_inquiries);
        }

        // POST: Inquiries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "inq_id,inq_content,inq_date,inq_from,inq_to,thread_id")] tbl_inquiries tbl_inquiries)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_inquiries).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.inq_from = new SelectList(db.tbl_accounts, "account_id", "account_email", tbl_inquiries.inq_from);
            ViewBag.inq_to = new SelectList(db.tbl_accounts, "account_id", "account_email", tbl_inquiries.inq_to);
            ViewBag.thread_id = new SelectList(db.tbl_threads, "thread_id", "thread_title", tbl_inquiries.thread_id);
            return View(tbl_inquiries);
        }

        // GET: Inquiries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_inquiries tbl_inquiries = db.tbl_inquiries.Find(id);
            if (tbl_inquiries == null)
            {
                return HttpNotFound();
            }
            return View(tbl_inquiries);
        }

        // POST: Inquiries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_inquiries tbl_inquiries = db.tbl_inquiries.Find(id);
            db.tbl_inquiries.Remove(tbl_inquiries);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

capstone_project/Controllers/VendorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using capstone_project.Models;
using System.IO;

namespace capstone_project.Controllers
{
    public class VendorController : Controller
    {
        private capstone_mwdEntities db = new capstone_mwdEntities();
        // GET: Admin
        public ActionResult Index()
        {
            try
            {
                string account = Session["Account_id"].ToString();


                string input = Request.Form["search-input"];
                var x = input == null || input == "" ? db.tbl_products.Where(y => y.product_owner.ToString() != account).ToList() : db.tbl_products.Where(i => i.product_name.Contains(input) || i.product_desc.Contains(input)).Where(y => y.product_owner.ToString() != account).ToList();
                return View(x);
            }
            catch
            {
                string account = Session["Account_id"].ToString();
                string input = Request.Form["search-input"];
                var x = input == null || input == "" ? db.tbl_products.Where(y => y.product_owner.ToString() != account).ToList() : db.tbl_products.Where(i => i.product_name.Contains(input) || i.product_desc.Contains(input)).Where(y => y.product_owner.ToString() != account).ToList();
                return View(x);
            }

        }

        public ActionResult my_products()
        {
            try
            {
                string account = Session["Account_id"].ToString();
                var x = db.tbl_products.Where(y => y.product_owner.ToString() == account).ToList();
                return View(x);
            }
            catch
            {
                var x = db.tbl_products.ToList();
                return View(x);
            }

        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult faq()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult profile()
        {
            int buyer = int.Parse(Session["Account_id"].ToString());
            var account = db.tbl_accounts.Where(x => x.account_id == buyer).ToList();
            ViewBag.account = db.tbl_accounts.Where(x => x.account_id == buyer).ToList();
            return View(account);
        }

        public ActionResult account_request()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


        public ActionResult discount()
        {
            int seller = int.Parse(Session["Account_id"].ToString());
            var discount = db.tbl_discounts.Where(y => y.account_id == seller).ToList();
            return View(discount);
        }

        public ActionResult reports()
        {
            int seller = int.Parse(Session["Account_id"].ToString());
            var record = db.tbl_cart.Where(y => y.tbl_products.product_owner == seller).ToList();
            //db.tbl_transactions.Where(x => x.tbl_products.product_owner == seller).Where(x => x.trans_status != "cart").ToList();

            ViewBag.cart = db.tbl_cart.Where(y => y.tbl_products.product_owner == seller).ToList();
            return View(record);
        }

        public ActionResult add_item()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [Route("execute_add")]
        [HttpPost]
        public void execute_add(string name, string price, string desc, string quantity, string img)
        {
            string image = img == "" ? @"\\upload.png" : img;

            string[] words = image.Split('\\');
          

            tbl_products prod = new tbl_products();
            prod.product_name = name;
            prod.product_price = int.Parse(price);
            prod.product_desc = desc;
            prod.product_quantity = int.Parse(quantity);
            prod.prod_img = words[2];
            prod.product_owner = int.Parse(Session["Account_id"].ToString());
            db.tbl_products.Add(prod);
            db.SaveChanges();
            
        }

        public JsonResult Upload()
        {
            var ctr = db.tbl_products.OrderByDescending(u => u.product_id).FirstOrDefault().product_id;

            string target = Server.MapPath(@"\images\products\" + ctr + @"\");
     

            if (!System.IO.Directory.Exists(target))
            {
                System.IO.Directory.CreateDirectory(target);
            }

            for (int i = 0; i < 1; i++)
            {
                HttpPostedFileBase file = Request.Files[i]; //Uploaded file
                                                            //Use the following properties to get file's name, size and MIMEType
                int fileSize = file.ContentLength;
                string fileName = file.FileName;
                string mimeType = file.ContentType;
                System.IO.Stream fileContent = file.InputStream;
                //To save file, use SaveAs method
                file.SaveAs(target + fileName); //File will be saved in application root
            }

            return Json("Uploaded " + Request.Files.Count + " files");
        }

        public ActionResult edit_item(int? id)
        {
            var item = db.tbl_products.Where(x => x.product_id == id).ToList();
            return View(item);
        }

        [Route("execute_edit")]
        [HttpPost]
        public void execute_edit(string name, string price, string desc, string quantity, string img, int id)
        {
            string image = img == "" ? @"\\upload.png" : img;

            tbl_products prod = db.tbl_products.Find(id);
            prod.product_name = name;
            prod.product_price = int.Parse(price);
            prod.product_desc = desc;
            prod.product_quantity = int.Parse(quantity);
            if (img != "")
            {
                string[] words = img.Split('\\');
                prod.prod_img = words[2];
            }
      
            db.SaveChanges();

        }


        [Route("create_discount")]
        [HttpPost]
        public void create_discount(string code, string amount)
        {
            int seller = int.Parse(Session["Account_id"].ToString());
            tbl_discounts disc = new tbl_discounts();
            disc.discount_code = code;
            disc.discount_amount = Convert.ToDouble(amount);
            disc.account_id = seller;
            db.tbl_discounts.Add(disc);
            db.SaveChanges();

        }
        public JsonResult EditImage(string id)
        {
            int user = int.Parse(id);
            var ctr = db.tbl_products.Find(user).product_id;

            //~/ images / products / @Html.DisplayFor(modelItem => item.product_id) /
            string targetPathProfilePic = Server.MapPath(@"\images\products\" + ctr + "\\");

            System.IO.DirectoryInfo di = new DirectoryInfo(targetPathProfilePic);

            if (System.IO.Directory.Exists(targetPathProfilePic))
            {
                foreach (FileInfo file in di.GetFiles())
                {
                    file.Delete();
                }
            }
            else
            {
                System.IO.Directory.CreateDirectory(targetPathProfilePic);
            }

            for (int i = 0; i < 1; i++)
            {
                HttpPostedFileBase file = Request.Files[i]; //Uploaded file

                int fileSize = file.ContentLength;
                string fileName = file.FileName;
                string mimeType = file.ContentType;
                System.IO.Stream fileContent = file.InputStream;
                //To save file, use SaveAs method
                file.SaveAs(targetPathProfilePic + fileName); //File will be saved in application root
            }
            return Json("Uploaded " + Request.Files.Count + " files");
        }


        public ActionResult inquiry()
        {
            int from = int.Parse(Session["Account_id"].ToString());
            var x = db.tbl_inquiries.Where(y => y.inq_from == from || y.inq_to == from).OrderBy(a => a.thread_id).ToList();
            return View(x);
        }

        public ActionResult new_inquiry()
        {
            int from = int.Parse(Session["Account_id"].ToString());
            var obj = db.tbl_accounts.Where(x => x.account_type != 3).Where(x => x.account_id != from).ToList();
            var dist = obj.Distinct();
            return View(dist);
        }


        public ActionResult send_new()
        {
            int from = int.Parse(Session["Account_id"].ToString());
            tbl_threads thread = new tbl_threads();
            thread.thread_title = Request.Form["title"];
            db.tbl_threads.Add(thread);
            db.SaveChanges();

            var thread_id = db.tbl_threads.OrderByDescending(x => x.thread_id).FirstOrDefault().thread_id;

            tbl_inquiries inq = new tbl_inquiries();
            inq.thread_id = thread_id;
            inq.inq_content = Request.Form["message"];
            inq.inq_date = DateTime.Now;
            inq.inq_from = from;
            inq.inq_to = int.Parse(Request.Form["account_dest"]);
            db.tbl_inquiries.Add(inq);
            db.SaveChanges();
            return RedirectToAction("inquiry");
        }

        [Route("ChangeToPaid")]
        [HttpPost]
        public void ChangeToPaid(string trans_id)
        {
            tbl_transactions obj_trans = db.tbl_transactions.Find(int.Parse(trans_id));
            obj_trans.trans_status = "Paid";
            db.SaveChanges();

        }

        public ActionResult reply()
        {

            int from = int.Parse(Session["Account_id"].ToString());
            tbl_inquiries inq = new tbl_inquiries();

capstone_project/Views/Vendor/about.cshtml
@{
    Layout = "~/Views/Shared/_LayoutPageVendor.cshtml";
}


<div class="w3-content" style="padding-bottom:10vh">
    <!-- The Grid -->
    <div class="w3-row-padding">

        <div class="row w3-container" style="border-bottom:solid; border-bottom-color:#808080">
            <div class="col-sm-12">
                <p class="" style="height: 8vh; font-size: 3vh; text-align: left; font-family:'Courier New'"> About Page: What is MWD</p>
            </div>
        </div>

        <div class="row w3-container" style="margin-top:2%">
            <div class="col-sm-12">
                <p class="" style="height: 8vh; font-size: 2vh; text-align: left; font-family:'Courier New'">
                    This website is created for Capstone 3. The details in this about page is still under construcion therefore the content is not yet final. But we are praying that we will pass capstone 2 and 3 this term.
                </p>
            </div>

            <div class="col-sm-12" style="margin-top:5%">
                <p class="" style="height: 8vh; font-size: 2vh; text-align: left; font-family:'Courier New'">
                    <b style="font-weight:bold"> Created and Designed by: </b> <br /> Defiesta, Ma. Laurrette Angelica Joice A. <br /> Estrada, Diana G. <br /> Veloso, Art Nico S.
                </p>
            </div>

        </div>
    </div>
</div>

capstone_project/Views/Vendor/add_item.cshtml
@{
    Layout = "~/Views/Shared/_LayoutPageVendor.cshtml";
}



<div class="w3-content" style="">
    <!-- The Grid -->
    <div class="w3-row-padding">

        <div class="row w3-container" style="border-bottom:solid; border-bottom-color:#808080">
            <div class="col-sm-12">
                <p class="" style="height: 8vh; font-size: 5vh; text-align: left; font-family:'Courier New';color:black"> New Product Page</p>
            </div>
        </div>

        <div class="row w3-container" style="margin-top:2%">
            <div class="col-sm-12">
                <div class="col-sm-5" style="">
                    <p class="" style="height: 8vh; font-size: 3vh; text-align: left; font-family:'Courier New'; text-align:center">
                        <input type="hidden" name="imgSource" id="imgSource">
                        <img src="~/images/upload.png" style="width:30vw; height:50vh" name="imageContainer" id="imageContainer" alt="Avatar">

                        <input type="file" class="form-control" name="imageSrc" id="imageSrc" onchange="previewFile()" style="margin:3vh"><br>
                    </p>
                </div>
                <div class="col-sm-7">
                    <div class="col-sm-12" style="margin-bottom:2vh;  border-bottom:solid; border-bottom-color:gray">
                        <div class="col-sm-12" style="margin-bottom:2vh">
                            <p style="color:#000000"><i class="fa fa-address-card fa-fw w3-margin-right w3-large w3-text-teal"></i> Item Information</p>
                        </div>
                        <div class="col-sm-12" style="margin-bottom:2vh">
                            <input type="text" class="form-control col-xs-2" placeholder="Item Name" id="name">
                        </div>
                        <div class="col-sm-12" style="margin-bottom:2vh">
                            <p><input type="text" class="form-control" placeholder="Item Price" id="price"></p>
                        </div>
                        <div class="col-sm-12" style="margin-bottom:2vh">
                            <p><textarea class="form-control" placeholder="Description" id="desc" style="height:18vh"></textarea></p>
                        </div>
                        <div class="col-sm-12" style="margin-bottom:2vh">
                            <p><input type="text" class="form-control" placeholder="Quantity" id="quantity"></p>
                        </div>


                    </div>
                    <div class="col-sm-12" style=" margin-top: 1vh" id="register_div">
                        <button type="button" class="form-control col-xs-12" style="font-size:2vh;background-color:cornflowerblue;width:100%; color:aliceblue;" onclick="add()"> Add Item  </button>
                    </div>
                </div>
            </div>
           
     
        </div>
    </div>
</div>


<script>



    function previewFile() {
        // var preview = document.querySelector('img');

        var preview = document.getElementById("imageContainer");
        var file = document.getElementById("imageSrc").files[0];
        // document.querySelector('input[name=image]').files[0];
        var imageSourceVar = document.getElementById("imgSource");
        var reader = new FileReader();

        reader.addEventListener("load", function () {
            document.getElementById("imageContainer").src = reader.result;
            document.getElementById("imgSource").value = reader.result;
        }, false);

        if (file) {
            reader.readAsDataURL(file);
        }
    }

    function add() {

        var name = document.getElementById("name").value;
        var price = document.getElementById("price").value;
        var desc = document.getElementById("desc").value;
        var quantity = document.getElementById("quantity").value;
        var img = document.getElementById("imageSrc").value;

        //var img = $('#imageContainer').attr('src');

        $.ajax({
            method: "POST",
            url: "@Url.Action("execute_add", "Vendor")",
            data: { name: name, price: price, desc: desc, quantity: quantity, img: img },
            success: function (result) {
                alert("Item Added");
            },
            failed: function (result) {
                console.log("Failed");
            },
        });

        var formdata = new FormData(); //FormData object
        var fileInput = document.getElementById('imageSrc');
      
        formdata.append(fileInput.files[0].name, fileInput.files[0]);

        //Creating an XMLHttpRequest and sending
        var xhr = new XMLHttpRequest();
        xhr.open('POST', '/Vendor/Upload');
        xhr.send(formdata);
        xhr.onreadystatechange = function () {
            if (xhr.readyState == 4 && xhr.status == 200) {
                //alert(xhr.responseText);

            }
        }
        EditImg();
    }

    function EditImg() {
        var formdata = new FormData(); //FormData object
        var fileInput = document.getElementById('imageSrc');
        var id = document.getElementById("id").value;

        formdata.append(fileInput.files[0].name, fileInput.files[0]);
        //Creating an XMLHttpRequest and sending
        var xhr = new XMLHttpRequest();
        xhr.open('POST', '/Vendor/EditImage?id=' + id);
        xhr.send(formdata);
        xhr.onreadystatechange = function () {
            if (xhr.readyState == 4 && xhr.status == 200) {
                //alert(xhr.responseText);
            }
        }
    }

</script>

capstone_project/Views/Vendor/edit_item.cshtml
@{
    Layout = "~/Views/Shared/_LayoutPageVendor.cshtml";
}

@model IEnumerable<capstone_project.Models.tbl_products>
@foreach (var item in Model)
{
    <div class="w3-content" style="">
        <!-- The Grid -->
        <div class="w3-row-padding">

            <div class="row w3-container" style="border-bottom:solid; border-bottom-color:#808080">
                <div class="col-sm-12">
                    <p class="" style="height: 8vh; font-size: 5vh; text-align: left; font-family:'Courier New';color:black"> Edit Product Page</p>
                </div>
            </div>

            <div class="row w3-container" style="margin-top:2%">
                <div class="col-sm-12">
                    <div class="col-sm-5" style="">
                        <p class="" style="height: 8vh; font-size: 3vh; text-align: left; font-family:'Courier New'; text-align:center">
                            <input type="hidden" name="imgSource" id="imgSource">
                            <img src="~/images/products/@Html.DisplayFor(modelItem => item.product_id)/@Html.DisplayFor(modelItem => item.prod_img)" style="width:30vw; height:50vh" name="imageContainer" id="imageContainer" alt="Avatar">

                            <input type="file" class="form-control" name="imageSrc" id="imageSrc" onchange="previewFile()" style="margin:3vh"><br>
                        </p>
                    </div>
                    <div class="col-sm-7">
                        <div class="col-sm-12" style="margin-bottom:2vh;  border-bottom:solid; border-bottom-color:gray">
                            <div class="col-sm-12" style="margin-bottom:2vh">
                                <p style="color:#000000"><i class="fa fa-address-card fa-fw w3-margin-right w3-large w3-text-teal"></i> Item Information</p>
                            </div>
                            <div class="col-sm-12" style="margin-bottom:2vh">
                                <input type="text" class="form-control col-xs-2" placeholder="Item Name" id="name" value="@item.product_name">
                                <input type="text" class="form-control col-xs-2" placeholder="Item Name" id="id" value="@item.product_id" style="display:none">
                            </div>
                            <div class="col-sm-12" style="margin-bottom:2vh">
                                <p><input type="text" class="form-control" placeholder="Item Price" id="price" value="@item.product_price"></p>
                            </div>
                            <div class="col-sm-12" style="margin-bottom:2vh">
                                <p><textarea class="form-control" placeholder="Description" id="desc" style="height:18vh"> @item.product_desc</textarea></p>
                            </div>
                            <div class="col-sm-12" style="margin-bottom:2vh">
                                <p><input type="text" class="form-control" placeholder="Quantity" id="quantity" value="@item.product_quantity"> </p>
                            </div>


                        </div>
                        <div class="col-sm-12" style=" margin-top: 1vh" id="register_div">
                            <button type="button" class="form-control col-xs-12" style="font-size:2vh;background-color:cornflowerblue;width:100%; color:aliceblue;" onclick="edit()"> Edit Item  </button>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
}

    <script>

    
    function previewFile() {
        // var preview = document.querySelector('img');

        var preview = document.getElementById("imageContainer");
        var file = document.getElementById("imageSrc").files[0];
        // document.querySelector('input[name=image]').files[0];
        var imageSourceVar = document.getElementById("imgSource");
        var reader = new FileReader();

        reader.addEventListener("load", function () {
            document.getElementById("imageContainer").src = reader.result;
            document.getElementById("imgSource").value = reader.result;
        }, false);

        if (file) {
            reader.readAsDataURL(file);
        }
    }

    function EditImg() {
        var formdata = new FormData(); //FormData object
        var fileInput = document.getElementById('imageSrc');
        var id = document.getElementById("id").value;

        formdata.append(fileInput.files[0].name, fileInput.files[0]);
        //Creating an XMLHttpRequest and sending
        var xhr = new XMLHttpRequest();
        xhr.open('POST', '/Vendor/EditImage?id=' + id);
        xhr.send(formdata);
        xhr.onreadystatechange = function () {
            if (xhr.readyState == 4 && xhr.status == 200) {
                //alert(xhr.responseText);
            }
        }
    }



    function edit() {
        var id = document.getElementById("id").value;
        var name = document.getElementById("name").value;
        var price = document.getElementById("price").value;
        var desc = document.getElementById("desc").value;
        var quantity = document.getElementById("quantity").value;
        var img = document.getElementById("imageSrc").value;

        //var img = $('#imageContainer').attr('src');
        
        $.ajax({
            method: "POST",
            url: "@Url.Action("execute_edit", "Vendor")",
            data: { name: name, price: price, desc: desc, quantity: quantity, img: img, id: id },
            success: function (result) {
                alert("Item Edited");
            },
            failed: function (result) {
                console.log("Failed");
            },
        });
        EditImg();
    }

    </script>

capstone_project/Views/Vendor/reports.cshtml
@{
    Layout = "~/Views/Shared/_LayoutPageVendor.cshtml";
}

@model IEnumerable<capstone_project.Models.tbl_cart>

<div class="w3-content" style="">
    <!-- The Grid -->
    <div class="w3-row-padding">

        <div class="row w3-container" style="border-bottom:solid; border-bottom-color:#808080">
            <div class="col-sm-12">
                <p class="" style="height: 8vh; font-size: 3vh; text-align: left; font-family:'Courier New'; color:black"> Transaction Reports</p>
            </div>
        </div>
        @foreach (var item in Model)
        {
            <div class="row w3-container">
                <div class="col-sm-12" style="border:solid; border-color:dimgray; margin-top:2vh; height:25vh">
                    <div class="col-sm-10">
                        <p class="" style="height: 6vh; font-size: 2vh; text-align: left; font-family:'Courier New'; margin-top:3vh">
                            <b style="font-weight:900">Product Name: </b> @item.tbl_products.product_name<br />
                            <b style="font-weight:900"> Buyer Name: </b> @item.tbl_transactions.tbl_accounts.tbl_personalInformations.Where(x => x.account_id == item.tbl_transactions.trans_buyer).FirstOrDefault().personal_firstName  @item.tbl_transactions.tbl_accounts.tbl_personalInformations.Where(x => x.account_id == item.tbl_transactions.trans_buyer).FirstOrDefault().personal_lastName  <br />
                            <b style="font-weight:900"> Transaction Status: </b>
                            @item.tbl_transactions.trans_status
                            <br />
                            @if (@item.tbl_transactions.trans_status == "For Delivery")
                            {
                                <div class="col-sm-12" style=" margin-top: 6vh" id="register_div">
                                    <button type="button" class="form-control col-xs-12" style="font-size:2vh;background-color:cornflowerblue;width:100%; color:aliceblue;" onclick="ChangeToPaid(@item.tbl_transactions.trans_id)"> Mark as Paid </button>
                                </div>
                            }
                        </p>
                    </div>
                    <div class="col-sm-2" style="height: 6vh; font-size: 4vh; text-align: right; font-family:'Courier New'; margin-top:2vh; font-weight:bolder">
                        <img src="~/images/products/@item.tbl_products.product_id/@item.tbl_products.prod_img" style="height:20vh; width:100%; min-height:20vh" alt="Avatar">
                    </div>
                </div>
                
            </div>
        }
    </div>
</div>

<script>
    function answer(id) {
        if (document.getElementById(id).style.display == "none") {
            $("#" + id).css("display", "block");
        } else {
            $("#" + id).css("display", "none");
        }
    }


    
    function ChangeToPaid(id) {
        var trans_id = id;
        $.ajax({
            method: "POST",
            url: "@Url.Action("ChangeToPaid", "Vendor")",
            data: { trans_id: trans_id},
            success: function (result) {
                alert("Transaction Paid");
                location.reload();
            },
            failed: function (result) {
                console.log("Failed");
            },
        });
    }

</script>