capstone_project/Controllers/DistributorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using capstone_project.Models;
using System.Configuration;
using Stripe;
using System.IO;

namespace capstone_project.Controllers
{
    public class DistributorController : Controller
    {
        private capstone_mwdEntities db = new capstone_mwdEntities();
        // GET: Admin
        public ActionResult Index()
        {
            try
            {
                string account = Session["Account_id"].ToString();


                string input = Request.Form["search-input"];
                var x = input == null || input == "" ? db.tbl_products.Where(y => y.product_owner.ToString() != account).ToList() : db.tbl_products.Where(i => i.product_name.Contains(input) || i.product_desc.Contains(input)).Where(y => y.product_owner.ToString() != account).ToList();
                return View(x);
            }
            catch
            {
                string account = Session["Account_id"].ToString();
                string input = Request.Form["search-input"];
                var x = input == null || input == "" ? db.tbl_products.Where(y => y.product_owner.ToString() != account).ToList() : db.tbl_products.Where(i => i.product_name.Contains(input) || i.product_desc.Contains(input)).Where(y => y.product_owner.ToString() != account).ToList();
                return View(x);
            }

        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult faq()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult profile()
        {
            int buyer = int.Parse(Session["Account_id"].ToString());
            var account = db.tbl_accounts.Where(x => x.account_id == buyer).ToList();
            ViewBag.account = db.tbl_accounts.Where(x => x.account_id == buyer).ToList();
            return View(account);
        }

        public ActionResult account_request()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult reports()
        {
            int seller = int.Parse(Session["Account_id"].ToString());
            var record = db.tbl_cart.Where(y => y.tbl_products.product_owner == seller).ToList();
            //db.tbl_transactions.Where(x => x.tbl_products.product_owner == seller).Where(x => x.trans_status != "cart").ToList();

            ViewBag.cart = db.tbl_cart.Where(y => y.tbl_products.product_owner == seller).ToList();
            return View(record);
        }

        public ActionResult add_item()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        [Route("execute_add")]
        [HttpPost]
        public void execute_add(string name, string price, string desc, string quantity, string img)
        {
            string image = img == "" ? @"\\upload.png" : img;
            string[] words = image.Split('\\');
      

            tbl_products prod = new tbl_products();
            prod.product_name = name;
            prod.product_price = int.Parse(price);
            prod.product_desc = desc;
            prod.product_quantity = int.Parse(quantity);
            prod.prod_img = words[2];
            prod.product_owner = int.Parse(Session["Account_id"].ToString());
            db.tbl_products.Add(prod);
            db.SaveChanges();
            
        }

        public JsonResult Upload()
        {
            var ctr = db.tbl_products.OrderByDescending(u => u.product_id).FirstOrDefault().product_id;

            string target = Server.MapPath(@"\images\products\" + ctr + @"\");

            if (!System.IO.Directory.Exists(target))
            {
                System.IO.Directory.CreateDirectory(target);
            }

            for (int i = 0; i < 1; i++)
            {
                HttpPostedFileBase file = Request.Files[i]; //Uploaded file
                                                            //Use the following properties to get file's name, size and MIMEType
                int fileSize = file.ContentLength;
                string fileName = file.FileName;
                string mimeType = file.ContentType;
                System.IO.Stream fileContent = file.InputStream;
                //To save file, use SaveAs method
                file.SaveAs(target + fileName); //File will be saved in application root
            }

            return Json("Uploaded " + Request.Files.Count + " files");
        }
        public ActionResult my_products()
        {
            try
            {
                string account = Session["Account_id"].ToString();
                var x = db.tbl_products.Where(y => y.product_owner.ToString() == account).ToList();
                return View(x);
            }
            catch
            {
                var x = db.tbl_products.ToList();
                return View(x);
            }
        }

        public ActionResult cart()
        {
            int buyer = int.Parse(Session["Account_id"].ToString());
            var cart = db.tbl_cart.Where(c => c.tbl_transactions.trans_status == "cart").Where(c => c.tbl_transactions.trans_buyer == buyer).ToList();

            ViewBag.sum = db.tbl_cart.Where(c => c.tbl_transactions.trans_status == "cart").Where(c => c.tbl_transactions.trans_buyer == buyer).Sum(c => c.tbl_products.product_price * c.cart_quantity);
            ViewBag.sumTax = db.tbl_cart.Where(c => c.tbl_transactions.trans_status == "cart").Where(c => c.tbl_transactions.trans_buyer == buyer).Sum(c => c.tbl_products.product_price * c.cart_quantity) + 500;
            return View(cart);
        }


        [Route("add_cart")]
        [HttpPost]
        public void add_cart(string prodId, int quantity)
        {
            tbl_transactions trans = new tbl_transactions();
            tbl_cart cart = new tbl_cart();
            int buyer = int.Parse(Session["Account_id"].ToString());

            var transCount = db.tbl_transactions.Where(t => t.trans_status == "cart").Where(t => t.trans_buyer == buyer).ToList();
            tbl_transactions obj_trans = new tbl_transactions();
            tbl_cart obj_cart = new tbl_cart();

            if (transCount.Count > 0)
            {
                var transCount2 = db.tbl_transactions.Where(t => t.trans_status == "cart").Where(t => t.trans_buyer == buyer).OrderByDescending(t => t.trans_id).FirstOrDefault();


                obj_cart.trans_id = transCount2.trans_id;
                obj_cart.product_id = int.Parse(prodId);
                obj_cart.cart_quantity = quantity;
                db.tbl_cart.Add(obj_cart);
                db.SaveChanges();

            }
            else
            {
                //obj_trans.trans_product = int.Parse(prodId);
                obj_trans.trans_buyer = buyer;
                obj_trans.trans_status = "cart";

                db.tbl_transactions.Add(obj_trans);
                db.SaveChanges();

                var transCount2 = db.tbl_transactions.Where(t => t.trans_status == "cart").Where(t => t.trans_buyer == buyer).OrderByDescending(t => t.trans_id).FirstOrDefault();


                obj_cart.trans_id = transCount2.trans_id;
                obj_cart.product_id = int.Parse(prodId);
                obj_cart.cart_quantity = quantity;
                db.tbl_cart.Add(obj_cart);
                db.SaveChanges();

            }

            //tbl_accounts tbl_accounts = db.tbl_accounts.Find(int.Parse(id));
            //tbl_accounts.account_status = 2;
            //db.SaveChanges();

        }


        [Route("remove_cart")]
        [HttpPost]
        public void remove_cart(string cart)
        {
            tbl_cart obj_cart = db.tbl_cart.Find(int.Parse(cart));
            db.tbl_cart.Remove(obj_cart);
            db.SaveChanges();

        }


        public ActionResult Charge(string stripeEmail, string stripeToken)
        {
            var customers = new StripeCustomerService();
            var charges = new StripeChargeService();

            var customer = customers.Create(new StripeCustomerCreateOptions
            {
                Email = stripeEmail,
                SourceToken = stripeToken
            });

            var charge = charges.Create(new StripeChargeCreateOptions
            {
                Amount = int.Parse(Request.Form["stripeAmount"]),//charge in cents
                Currency = "usd",
                CustomerId = customer.Id
            });

            // further application specific code goes here
            pay_now();
            return RedirectToAction("payment_success");
        }

        public ActionResult payment_success()
        {

            return View();
        }

        public ActionResult check_out()
        {

            var stripePublishKey = "pk_test_NLldSQJtWpv4aufQyoQ4Jfqw";
            ViewBag.StripePublishKey = stripePublishKey;

            int buyer = int.Parse(Session["Account_id"].ToString());
            var cart = db.tbl_cart.Where(c => c.tbl_transactions.trans_status == "cart").Where(c => c.tbl_transactions.trans_buyer == buyer).ToList();

            ViewBag.sum = db.tbl_cart.Where(c => c.tbl_transactions.trans_status == "cart").Where(c => c.tbl_transactions.trans_buyer == buyer).Sum(c => c.tbl_products.product_price * c.cart_quantity);
            ViewBag.sumTax = db.tbl_cart.Where(c => c.tbl_transactions.trans_status == "cart").Where(c => c.tbl_transactions.trans_buyer == buyer).Sum(c => c.tbl_products.product_price * c.cart_quantity) + 500;
            ViewBag.sumTaxStripe = ViewBag.sumTax * 100;
            return View(cart);
        }


        [Route("verify")]

capstone_project/Controllers/InquiriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using capstone_project.Models;

namespace capstone_project.Controllers
{
    public class InquiriesController : Controller
    {
        private capstone_mwdEntities db = new capstone_mwdEntities();

        // GET: Inquiries
        public ActionResult Index()
        {
            var tbl_inquiries = db.tbl_inquiries.Include(t => t.tbl_accounts).Include(t => t.tbl_accounts1).Include(t => t.tbl_threads);
            return View(tbl_inquiries.ToList());
        }

        // GET: Inquiries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_inquiries tbl_inquiries = db.tbl_inquiries.Find(id);
            if (tbl_inquiries == null)
            {
                return HttpNotFound();
            }
            return View(tbl_inquiries);
        }

        // GET: Inquiries/Create
        public ActionResult Create()
        {
            ViewBag.inq_from = new SelectList(db.tbl_accounts, "account_id", "account_email");
            ViewBag.inq_to = new SelectList(db.tbl_accounts, "account_id", "account_email");
            ViewBag.thread_id = new SelectList(db.tbl_threads, "thread_id", "thread_title");
            return View();
        }

        // POST: Inquiries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "inq_id,inq_content,inq_date,inq_from,inq_to,thread_id")] tbl_inquiries tbl_inquiries)
        {
            if (ModelState.IsValid)
            {
                db.tbl_inquiries.Add(tbl_inquiries);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.inq_from = new SelectList(db.tbl_accounts, "account_id", "account_email", tbl_inquiries.inq_from);
            ViewBag.inq_to = new SelectList(db.tbl_accounts, "account_id", "account_email", tbl_inquiries.inq_to);
            ViewBag.thread_id = new SelectList(db.tbl_threads, "thread_id", "thread_title", tbl_inquiries.thread_id);
            return View(tbl_inquiries);
        }

        // GET: Inquiries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_inquiries tbl_inquiries = db.tbl_inquiries.Find(id);
            if (tbl_inquiries == null)
            {
                return HttpNotFound();
            }
            ViewBag.inq_from = new SelectList(db.tbl_accounts, "account_id", "account_email", tbl_inquiries.inq_from);
            ViewBag.inq_to = new SelectList(db.tbl_accounts, "account_id", "account_email", tbl_inquiries.inq_to);
            ViewBag.thread_id = new SelectList(db.tbl_threads, "thread_id", "thread_title", tbl_inquiries.thread_id);
            return View(tbl_inquiries);
        }

        // POST: Inquiries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "inq_id,inq_content,inq_date,inq_from,inq_to,thread_id")] tbl_inquiries tbl_inquiries)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_inquiries).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.inq_from = new SelectList(db.tbl_accounts, "account_id", "account_email", tbl_inquiries.inq_from);
            ViewBag.inq_to = new SelectList(db.tbl_accounts, "account_id", "account_email", tbl_inquiries.inq_to);
            ViewBag.thread_id = new SelectList(db.tbl_threads, "thread_id", "thread_title", tbl_inquiries.thread_id);
            return View(tbl_inquiries);
        }

        // GET: Inquiries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_inquiries tbl_inquiries = db.tbl_inquiries.Find(id);
            if (tbl_inquiries == null)
            {
                return HttpNotFound();
            }
            return View(tbl_inquiries);
        }

        // POST: Inquiries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_inquiries tbl_inquiries = db.tbl_inquiries.Find(id);
            db.tbl_inquiries.Remove(tbl_inquiries);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

capstone_project/Views/Distributor/Details.cshtml
@model capstone_project.Models.tbl_products


@{
    Layout = "~/Views/Shared/_LayoutPageDistributor.cshtml";
}


<div class="w3-content" style="">
    <!-- The Grid -->
    <div class="w3-row-padding">

        <div class="col-sm-12" style="background-color:white; border: solid 1px; border-color:darkgrey;">

            <div class="col-sm-5" style="">
                <div class="w3-col m2 w3-center col-sm-12" style="text-align:center; border-right: solid 1px; border-color:darkgrey;">
                    <input type="hidden" name="imgSource" id="imgSource">
                    <img src="~/images/products/@Model.product_id/@Model.prod_img" style="width:100%; min-height:60vh" name="imageContainer" id="imageContainer" alt="Avatar">
                </div>
            </div>
            <div class="col-sm-4" style="">
                <div class="w3-col m2 w3-center col-sm-12" style="text-align:left; margin-bottom:2vh; margin-top:2vh">
                    <p style="font-size: 3vh; font-family:'Courier New'; font-weight:bolder; color:black"><b> @Model.product_name</b></p>
                </div>
                <div class="w3-col m2 w3-center col-sm-12" style="text-align:left; margin-bottom:2vh; margin-top:2vh">
                    <p style="font-size: 2vh; font-family:'Courier New'; color:black">

                        <b style="font-weight:900">Price:</b>	@Model.product_price <br /><br />
                        @Model.product_desc
                    </p>
                </div>

                <div class="w3-col m2 w3-center col-sm-12" style="text-align:left; margin-bottom:2vh; margin-top:2vh">
                    <p style="font-size: 2vh; font-family:'Courier New'; color:black">

                        <b style="font-weight:900">Seller </b>:	@Model.tbl_accounts.tbl_personalInformations.Where(x => x.account_id == Model.tbl_accounts.account_id).FirstOrDefault().personal_lastName,  @Model.tbl_accounts.tbl_personalInformations.Where(x => x.account_id == Model.tbl_accounts.account_id).FirstOrDefault().personal_firstName
                        <br />
                        <b style="font-weight:900">Company </b>: 	@Model.tbl_accounts.tbl_companies.company_name


                    </p>
                </div>


            </div>
            <div class="col-sm-3" style="margin-bottom:2vh">
                <div class="col-sm-12" style="margin-bottom:2vh; margin-top:10%; text-align:right">

                    <select id="quantity" class="form-control col-xs-2" style="font-size: 3vh; text-align: left; font-family:'Courier New'; color:black; margin-bottom:2vh; width:5vw!important;  height:4vh ">
                        <option> 1 </option>
                        <option> 2 </option>
                        <option> 3 </option>
                        <option> 4 </option>
                    </select>

                </div>
                <div class="col-sm-12" style="margin-bottom:2vh">
                    <p class="" style="font-size: 3vh; text-align: left; font-family:'Courier New'; color:black; margin-bottom:2vh;">
                        <button type="button" class="form-control col-xs-2" style="background-color:#f0c14b; color:#000000; font-size: 2vh; text-align: center; font-family:'Courier New'" onclick="add(@Model.product_id)"> Add To Cart </button>
                    </p>
                </div>

            </div>

        </div>

    </div>

    <div class="col-sm-12" style="margin-top:1vh; border: solid 1px; border-color:darkgrey; background-color:white">
        <div class="col-sm-12" style="">
            <div class="col-sm-12" style="margin-top:5vh; margin-bottom:5vh;">
                <p style="font-size: 3vh; font-family:'Courier New'; font-weight:bolder; color:black"><b> Hot Sale for today </b></p>
            </div>
        </div>
        <div class="col-sm-12" style="">
            <div class="col-sm-12" style="margin-top:0vh; margin-bottom:5vh;">

                @{
                    int y = 0;
                    foreach (var item in ViewBag.products)
                    {
                        <div class="w3-col m2 w3-center col-sm-2" style="text-align:center">
                            <div style="width:100%; height:100% ;border-radius: 10%">
                                <a href="/Distributor/details?id=@item.product_id"><img style="width:100%; height:25vh ;" src="~/images/products/@item.product_id/@item.prod_img" name="imageContainer" id="imageContainer" alt="Avatar"></a>
                            </div>
                        </div>
                        y++;

                        if (y == 6)
                        {
                            break;
                        }
                    }
                }

            </div>
        </div>
    </div>
    <script>
        function add(id) {

            var prodId = id;
             var quantity = document.getElementById("quantity").value;

            $.ajax({
                method: "POST",
                url: "@Url.Action("add_cart", "User")",
                data: { prodId: prodId, quantity: quantity},
                success: function (result) {
                    alert("Item Added");
                },
                failed: function (result) {
                    console.log("Failed");
                },
            });
        }
    </script>

capstone_project/Views/Distributor/about.cshtml
@{
    Layout = "~/Views/Shared/_LayoutPageDistributor.cshtml";
}


<div class="w3-content" style="padding-bottom:10vh">
    <!-- The Grid -->
    <div class="w3-row-padding">

        <div class="row w3-container" style="border-bottom:solid; border-bottom-color:#808080">
            <div class="col-sm-12">
                <p class="" style="height: 8vh; font-size: 3vh; text-align: left; font-family:'Courier New'"> About Page: What is MWD</p>
            </div>
        </div>

        <div class="row w3-container" style="margin-top:2%">
            <div class="col-sm-12">
                <p class="" style="height: 8vh; font-size: 2vh; text-align: left; font-family:'Courier New'">
                    This website is created for Capstone 3. The details in this about page is still under construcion therefore the content is not yet final. But we are praying that we will pass capstone 2 and 3 this term.
                </p>
            </div>

            <div class="col-sm-12" style="margin-top:5%">
                <p class="" style="height: 8vh; font-size: 2vh; text-align: left; font-family:'Courier New'">
                    <b style="font-weight:bold"> Created and Designed by: </b> <br /> Defiesta, Ma. Laurrette Angelica Joice A. <br /> Estrada, Diana G. <br /> Veloso, Art Nico S.
                </p>
            </div>

        </div>
    </div>
</div>

capstone_project/Views/Distributor/contact.cshtml
@{
    Layout = "~/Views/Shared/_LayoutPageDistributor.cshtml";
}
<div class="w3-content" style="">
    <!-- The Grid -->
    <div class="w3-row-padding">

        <div class="row w3-container" style="border-bottom:solid; border-bottom-color:#808080">
            <div class="col-sm-12">
                <p class="" style="height: 8vh; font-size: 3vh; text-align: left; font-family:'Courier New'"> Contact Admin</p>
            </div>
        </div>

        <div class="row w3-container" style="margin-top:2%">
            <div class="col-sm-12">
                <p class="" style="height: 8vh; font-size: 3vh; text-align: left; font-family:'Courier New'">
                    <b style="font-weight:bold"> Email: </b> admin@gmail.com
                </p>
            </div>

            <div class="col-sm-12">
                <p class="" style="height: 8vh; font-size: 2vh; text-align: left; font-family:'Courier New'">
                    <b style="font-weight:bold"> Contact Number: </b> +63 927 123 45 67
                </p>
            </div>

            <div class="col-sm-12" style="">
                <p class="" style="height: 8vh; font-size: 2vh; text-align: left; font-family:'Courier New'">
                    <b style="font-weight:bold"> Created and Designed by: </b> <br /> Defiesta, Ma. Laurrette Angelica Joice A. <br /> Estrada, Diana G. <br /> Veloso, Art Nico S.
                </p>
            </div>

        </div>
    </div>
</div>

capstone_project/Views/Distributor/discount.cshtml
@{
    Layout = "~/Views/Shared/_LayoutPageDistributor.cshtml";
}

@model IEnumerable<capstone_project.Models.tbl_discounts>

<div class="w3-content" style="">
    <!-- The Grid -->
    <div class="w3-row-padding">

        <div class="row w3-container" style="border-bottom:solid; border-bottom-color:#808080">
            <div class="col-sm-12">
                <p class="" style="height: 8vh; font-size: 3vh; text-align: left; font-family:'Courier New'; color:black"> Discounts </p>
            </div>
        </div>
        <div class="col-sm-12" style="border:solid; border-color:dimgray; margin-top:2vh;" onclick="answer('1')">
            <div class="col-sm-10">
                <p class="" style="height: 6vh; font-size: 2vh; text-align: left; font-family:'Courier New'; margin-top:3vh">
                    Add New Discount
                </p>
            </div>
            <div class="col-sm-2" style="height: 6vh; font-size: 4vh; text-align: right; font-family:'Courier New'; margin-top:2vh; font-weight:bolder">
                +
            </div>
        </div>
        <div id="1" class="col-sm-12" style="border:solid; border-color:dimgray; margin-top:2vh; display:none;  background:dimgray;">
            <div class="col-sm-12" style="border:solid; border-color:dimgray; margin-top:2vh; height:10vh">
                <div class="col-sm-6">
                    <p class="" style="height: 6vh; font-size: 4vh; text-align: left; font-family:'Courier New'; margin-top:3vh">
                        <b style="font-weight:900; color:black">Discount Code: </b> <input type="text" id="disc_code" style="text-align:center" /><br />
                    </p>
                </div>
                <div class="col-sm-6">
                    <p class="" style="height: 6vh; font-size: 4vh; text-align: left; font-family:'Courier New'; margin-top:3vh">
                        <b style="font-weight:900; color:black">Discount Amount: </b> <input type="text" id="disc_amount" style="text-align:center"/> <br />
                    </p>
                </div>
            </div>
           <div class="col-sm-12" style="border:solid; border-color:dimgray; margin-top:2vh; height:10vh">
                <button type="button" class="form-control col-xs-12" style="font-size:2vh;background-color:cornflowerblue;width:100%; color:aliceblue;" onclick="add()"> Add Entry </button>
            </div>
        </div>
        @foreach (var item in Model)
        {
     
                <div class="col-sm-12" style="border:solid; border-color:dimgray; margin-top:2vh; height:10vh">
                    <div class="col-sm-6">
                        <p class="" style="height: 6vh; font-size: 2.5vh; text-align: left; font-family:'Courier New'; margin-top:3vh">
                            <b style="font-weight:900; color:black">Discount Code: </b> @item.discount_code<br />
                        </p>
                    </div>
                    <div class="col-sm-6">
                        <p class="" style="height: 6vh; font-size: 2.5vh; text-align: left; font-family:'Courier New'; margin-top:3vh">
                            <b style="font-weight:900; color:black">Discount Amount: </b> @item.discount_amount <br />
                        </p>
                    </div>
                </div>
          
        }
    </div>
</div>

<script>
    function answer(id) {
        if (document.getElementById(id).style.display == "none") {
            $("#" + id).css("display", "block");
        } else {
            $("#" + id).css("display", "none");
        }
    }

    function add() {
        var code = document.getElementById("disc_code").value;
        var amount = document.getElementById("disc_amount").value;
         $.ajax({
            method: "POST",
            url: "@Url.Action("create_discount", "Distributor")",
            data: { code: code, amount: amount},
            success: function (result) {
                alert("Discount Code Paid");
                location.reload();
            },
            failed: function (result) {
                console.log("Failed");
            },
        });
    }

</script>

capstone_project/Views/Distributor/my_products.cshtml
@model IEnumerable<capstone_project.Models.tbl_products>
@{
    Layout = "~/Views/Shared/_LayoutPageDistributor.cshtml";
}



<form action="." method="get">
    <header id="portfolio">


        <!-- Overlay effect when opening sidebar on small screens -->
        <div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>
        <div class="w3-container">
            <h1 style="text-align: center; font-style: italic;"><marquee> <b>Products on the market</b> </marquee></h1>
        </div>
    </header>
</form>
<br />
<div style="margin-bottom:5vh; margin-left:1.5vw" class="row">
    @foreach (var item in Model)
    {
        <div class="col-xs-3">
            <div style="font-style: italic;">
                <div class="card" style="width:18vw; min-height:8vh; margin-top:2vh">
                    <img src="~/images/products/@Html.DisplayFor(modelItem => item.product_id)/@Html.DisplayFor(modelItem => item.prod_img)" style="height:20vh; width:100%;" alt="Avatar">
                    @*<img class="card-img-top" src="~/images/upload.png" style="height:20vh; width:10vw; margin-left:25%" alt="Card image cap">*@
                    <div class="card-body">
                        <h5 class="card-title" style="font-size:2vh; font-weight:bolder">@Html.DisplayFor(modelItem => item.product_name)</h5>
                        <p class="card-text" style="font-size:2vh; text-align:justify; min-height: 20vh">
                            @item.product_desc.Substring(0, 150) ...<br />
                            Price: @Html.DisplayFor(modelItem => item.product_price)
                        </p>
                        <a href="/Distributor/edit_item?id=@Html.DisplayFor(modelItem => item.product_id)"><button type="button" class="form-control col-xs-12" style="font-size:2vh;background-color:cornflowerblue;width:100%; color:aliceblue"> Edit </button></a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

<div class="col-sm-12" style="margin-top:1vh; border: solid 1px; border-color:darkgrey; background-color:white">
    <div class="col-sm-12" style="">
        <div class="col-sm-12" style="margin-top:5vh; margin-bottom:5vh;">
            <p style="font-size: 3vh; font-family:'Courier New'; font-weight:bolder; color:black"><b> Hot Sale for today </b></p>
        </div>
    </div>
    <div class="col-sm-12" style="">
        <div class="col-sm-12" style="margin-top:0vh; margin-bottom:5vh;">

            @{
                int x = 0;
                foreach (var item in Model)
                {
                    <div class="w3-col m2 w3-center col-sm-2" style="text-align:center">
                        <div style="width:100%; height:100% ;border-radius: 10%">
                            <a href="/Distributor/edit_item?id=@Html.DisplayFor(modelItem => item.product_id)"><img style="width:100%; height:25vh ;" src="~/images/products/@Html.DisplayFor(modelItem => item.product_id)/@Html.DisplayFor(modelItem => item.prod_img)" name="imageContainer" id="imageContainer" alt="Avatar"></a>
                        </div>
                    </div>
                    x++;

                    if (x == 6)
                    {
                        break;
                    }
                }
            }

        </div>
    </div>
</div>